name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1
        with:
          host: course.prafdin.ru
          port: 3148
          username: katrin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u https-katice --password-stdin

            docker stop catty-container || true
            docker rm catty-container || true

            docker pull ghcr.io/https-katice/catty-reminders-app:${{ github.sha }}

            docker run -d --name catty-container -p 8181:8181 \
              ghcr.io/https-katice/catty-reminders-app:${{ github.sha }}